coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 10%

comment:
  layout: "diff, files"
  behavior: default
  require_changes: true
